server:
  port: 8082
spring:
  application:
    name: QUESTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/questionService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true