server:
  port: 8081
spring:
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/quizService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true